# Generated by Django 3.0.6 on 2020-05-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200530_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
    ]
